name = 'Lava'
name1 = "lava's"
name2 = '''lava
kumar
reddy'''
name3 = '''lava/nkumar/nreddy'''
# print(type(name),type(name1),type(name2))
# print(name)
# print(name1)
# print(name3)
# print(name.upper())
# print(name.lower())
# print(name.count("a"))
# print(name.index("v"))
# nameen = input("enter yur name:")
# lava = "hi {} thinara? akali ga unta {} lo order pattuko bro".format(nameen,"zomato")
# print(lava)

names = ['lava','reddy','sai','panth','kholi']
for i in names:
    print("hi {} thinra?".format(i))
# gmails = []
# yahoo = []
# for i in ["lava@gmail.com","reddy@yahoo.in","kumar@yahoo.in","siva@gmail.com"]:
#     if i.endswith(".com"):
#         gmails.append(i)
#     else:
#         yahoo.append(i)
# print(gmails)
# print(yahoo)

